# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# 换成你的社交链接，不需要的整段删掉即可
[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/tianming23"

    [social.params]
        icon = "brand-github"

# [[social]]
#     identifier = "twitter"
#     name       = "Twitter"
#     url        = "https://twitter.com/你的用户名"
#     [social.params]
#         icon = "brand-twitter"
